medical_warehouse_profile:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: "{{ env_var('DB_USER', 'test_user') }}"
      password: "{{ env_var('DB_PASSWORD', 'test_password') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME', 'test_db') }}"
      schema: public
      threads: 1
  target: dev